# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build
on: [push]
jobs:
    build:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
              with:
                  submodules: recursive
                  token: ${{ secrets.CI_TOKEN }}
            - uses: actions/setup-node@v1
              with:
                  node-version: "16"
            - run: yarn --cwd src/reader/ install
            - run: yarn install
            - run: yarn prettier
            - run: yarn test

            - name: Set up Docker Buildx
              id: buildx
              uses: docker/setup-buildx-action@v1

            - name: Docker meta
              id: docker_meta
              uses: docker/metadata-action@v3
              with:
                  images: ${{ secrets.DOCKER_ORGANIZATION }}/hardhat
                  tags: |
                      type=ref,event=branch
                      type=semver,pattern={{version}}
            - name: Login to Docker Hub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and push docker image
              id: docker_build
              uses: docker/build-push-action@v2
              with:
                  context: .
                  builder: ${{ steps.buildx.outputs.name }}
                  platforms: linux/amd64
                  tags: ${{ steps.docker_meta.outputs.tags }}
                  push: ${{ startsWith(github.ref, 'refs/tags/v') || (github.ref == 'refs/heads/develop') }}

    docker-delegate-server:
        name: Build and push docker image [delegate-server]
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
              with:
                  submodules: recursive
                  token: ${{ secrets.CI_TOKEN }}

            - uses: actions/setup-node@v1
              with:
                  node-version: "16"
            - run: yarn --cwd src/reader/ install

            - uses: actions/setup-node@v1
              with:
                  node-version: "16"
            - run: yarn install
            - run: yarn prepack

            - name: Set up Docker Buildx
              id: buildx
              uses: docker/setup-buildx-action@v1

            - name: Docker meta
              id: docker_meta
              uses: docker/metadata-action@v3
              with:
                  images: ${{ secrets.DOCKER_ORGANIZATION }}/delegate-server
                  tags: |
                      type=ref,event=branch
                      type=semver,pattern={{version}}
            - name: Login to Docker Hub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and push docker image
              id: docker_build
              uses: docker/build-push-action@v2
              with:
                  context: .
                  file: ./offchain/delegate_server/Dockerfile
                  builder: ${{ steps.buildx.outputs.name }}
                  platforms: linux/amd64
                  tags: ${{ steps.docker_meta.outputs.tags }}
                  push: ${{ startsWith(github.ref, 'refs/tags/v') || (github.ref == 'refs/heads/develop') }}

    docker-rollups-dispatcher:
        name: Build and push docker image [rollups-dispatcher]
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
              with:
                  submodules: recursive
                  token: ${{ secrets.CI_TOKEN }}

            - uses: actions/setup-node@v1
              with:
                  node-version: "16"
            - run: yarn --cwd src/reader/ install

            - uses: actions/setup-node@v1
              with:
                  node-version: "16"
            - run: yarn install
            - run: yarn prepack

            - name: Set up Docker Buildx
              id: buildx
              uses: docker/setup-buildx-action@v1

            - name: Docker meta
              id: docker_meta
              uses: docker/metadata-action@v3
              with:
                  images: ${{ secrets.DOCKER_ORGANIZATION }}/rollups-dispatcher
                  tags: |
                      type=ref,event=branch
                      type=semver,pattern={{version}}
            - name: Login to Docker Hub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and push docker image
              id: docker_build
              uses: docker/build-push-action@v2
              with:
                  context: .
                  file: ./offchain/offchain/Dockerfile
                  builder: ${{ steps.buildx.outputs.name }}
                  platforms: linux/amd64
                  tags: ${{ steps.docker_meta.outputs.tags }}
                  push: ${{ startsWith(github.ref, 'refs/tags/v') || (github.ref == 'refs/heads/develop') }}

    docker-query-server:
        name: Build and push docker image [query-server]
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
              with:
                  submodules: recursive
                  token: ${{ secrets.CI_TOKEN }}

            - uses: actions/setup-node@v1
              with:
                  node-version: "16"
            - run: yarn --cwd src/reader/ install

            - uses: actions/setup-node@v1
              with:
                  node-version: "16"
            - run: yarn install
            - run: yarn prepack

            - name: Set up Docker Buildx
              id: buildx
              uses: docker/setup-buildx-action@v1

            - name: Docker meta
              id: docker_meta
              uses: docker/metadata-action@v3
              with:
                  images: ${{ secrets.DOCKER_ORGANIZATION }}/query-server
                  tags: |
                      type=ref,event=branch
                      type=semver,pattern={{version}}
            - name: Login to Docker Hub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and push docker image
              id: docker_build
              uses: docker/build-push-action@v2
              with:
                  context: ./src/reader
                  file: ./src/reader/Dockerfile
                  builder: ${{ steps.buildx.outputs.name }}
                  platforms: linux/amd64
                  tags: ${{ steps.docker_meta.outputs.tags }}
                  push: ${{ startsWith(github.ref, 'refs/tags/v') || (github.ref == 'refs/heads/develop') }}

    docker-rollups-indexer:
        name: Build and push docker image [rollups-indexer]
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
              with:
                  submodules: recursive
                  token: ${{ secrets.CI_TOKEN }}

            - uses: actions/setup-node@v1
              with:
                  node-version: "16"
            - run: yarn --cwd src/reader/ install

            - uses: actions/setup-node@v1
              with:
                  node-version: "16"
            - run: yarn install
            - run: yarn prepack

            - name: Set up Docker Buildx
              id: buildx
              uses: docker/setup-buildx-action@v1

            - name: Docker meta
              id: docker_meta
              uses: docker/metadata-action@v3
              with:
                  images: ${{ secrets.DOCKER_ORGANIZATION }}/rollups-indexer
                  tags: |
                      type=ref,event=branch
                      type=semver,pattern={{version}}
            - name: Login to Docker Hub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and push docker image
              id: docker_build
              uses: docker/build-push-action@v2
              with:
                  context: .
                  file: ./offchain/indexer/Dockerfile
                  builder: ${{ steps.buildx.outputs.name }}
                  platforms: linux/amd64
                  tags: ${{ steps.docker_meta.outputs.tags }}
                  push: ${{ startsWith(github.ref, 'refs/tags/v') || (github.ref == 'refs/heads/develop') }}
